---
meta:
  name:    eden
  target:  bucc
  url:     https://192.168.50.6

  initial_version: 1.0.0

  go:
    version: "1.9"
    binary: eden
    cmd_module: .

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  starkandwayne
    repo:   eden
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       (( concat meta.name "-boshrelease" ))
    blob_success:  '(( concat ": New version of  was detected, and updated in master. <" meta.url "/teams//pipelines/| Cut a new release?>" ))'
    blob_failure:  '(( concat ": :airplane_arriving: <" meta.url "/teams//pipelines//jobs//builds/| Failed to update the blob for >" ))'
